# Generated by Django 5.2.1 on 2025-05-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=5)),
                ('distrito', models.CharField(max_length=2)),
                ('subdistrito', models.CharField(max_length=2)),
                ('setor', models.CharField(max_length=4)),
                ('num_quadra', models.CharField(max_length=3)),
                ('num_face', models.CharField(max_length=3)),
                ('seq_endereco', models.CharField(max_length=6)),
                ('seq_coletivo', models.CharField(max_length=6)),
                ('seq_especie', models.CharField(max_length=6)),
                ('especie_domicilio', models.TextField(choices=[('DOMICÍLIO PARTICULAR PERMANENTE OCUPADO', '1 - DOMICÍLIO PARTICULAR PERMANENTE OCUPADO'), ('DOMICÍLIO PARTICULAR IMPROVISADO OCUPADO', '5 - DOMICÍLIO PARTICULAR IMPROVISADO OCUPADO'), ('DOMICÍLIO COLETIVO COM MORADOR', '6 - DOMICÍLIO COLETIVO COM MORADOR')])),
                ('tipo', models.TextField(choices=[('CASA', '011 - CASA'), ('CASA DE VILA OU EM CONDOMÍNIO', '012 - CASA DE VILA OU EM CONDOMÍNIO'), ('APARTAMENTO', '013 - APARTAMENTO'), ('HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO', '014 - HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO'), ('HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA', '015 - HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA'), ('ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', '106 - ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO', '051 - TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO'), ('DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO', '052 - DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO'), ('OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS)', '053 - OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS)'), ('ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO, EXCETO TENDA OU BARRACA', '504 - ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO, EXCETO TENDA OU BARRACA'), ('ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', '505 - ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)', '506 - VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)'), ('ASILOS OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS', '061 - ASILO OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS'), ('HOTEL OU PENSÃO', '062 - HOTEL OU PENSÃO'), ('ALOJAMENTO', '063 - ALOJAMENTO'), ('PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR', '064 - PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR'), ('OUTRO', '065 - OUTRO'), ('ABRIGO, ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA', '606 - ABRIGO, ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA'), ('ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS', '607 - ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS'), ('CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR', '608 - CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR'), ('ORFANATO E SIMILAR', '609 - ORFANATO E SIMILAR'), ('UNIDADE DE INTERNAÇÃO DE MENORES', '610 - UNIDADE DE INTERNAÇÃO DE MENORES'), ('QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR', '611 - QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR')])),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
