# Generated by Django 5.2.1 on 2025-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo_ilhaprimeira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='rua_domicilio',
            field=models.TextField(choices=[('R. Marina do Sol', 'R. Marina do Sol'), ('R. Marina do Frade', 'R. Marina do Frade'), ('R. Marina dos Coqueiros', 'R. Marina dos Coqueiros'), ('R. Marina da Lua', 'R. Marina da Lua'), ('R. Marina do Bosque', 'R. Marina do Bosque'), ('R. Marina Porto Bali', 'R. Marina Porto Bali'), ('R. Marina das Flores', 'R. Marina das Flores'), ('R. Marina das Estrelas', 'R. Marina das Estrelas'), ('R. Marina Ponta Leste', 'R. Marina Ponta Leste')], null=True),
        ),
    ]
